services:
  _defaults:
    autowire: true

  App\:
    resource: '../src/*'
  
  App\Controller\OrderController:
    public: true
   
  App\Listener\OrderSmsListener:
    tags: [{name: 'app.event_listener', event: order.after_insert, method: sendSmsToCustomer, priority: 3}]

  App\Listener\OrderEmailsSubscriber: 
    tags: ['app.event_subscriber']  

  Symfony\Component\EventDispatcher\EventDispatcher: ~
    # public: true   
    # calls: 
    #   - method: "addListener"
    #     arguments:
    #       - order.after_insert
    #       - ['@App\Listener\OrderSmsListener','sendSmsToCustomer']
    #       - 3
    #   - method: "addSubscriber"
    #     arguments:
    #       - '@App\Listener\OrderEmailsSubscriber'